"""
PDF generation using reportlab.

All PDFs are generated in memory via BytesIO — never written to disk.
This is required for Lambda execution.
"""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.flowables import HRFlowable

BRAND_BLUE = colors.HexColor("#003580")
BRAND_ORANGE = colors.HexColor("#FF6B00")
LIGHT_GRAY = colors.HexColor("#F5F5F5")
DARK_GRAY = colors.HexColor("#333333")

styles = getSampleStyleSheet()

TITLE_STYLE = ParagraphStyle(
    "TitleStyle",
    parent=styles["Title"],
    textColor=BRAND_BLUE,
    fontSize=20,
    spaceAfter=6,
)
HEADING_STYLE = ParagraphStyle(
    "HeadingStyle",
    parent=styles["Heading2"],
    textColor=BRAND_BLUE,
    fontSize=13,
    spaceBefore=12,
    spaceAfter=4,
)
BODY_STYLE = ParagraphStyle(
    "BodyStyle",
    parent=styles["Normal"],
    fontSize=10,
    leading=15,
    textColor=DARK_GRAY,
)
SUBJECT_STYLE = ParagraphStyle(
    "SubjectStyle",
    parent=styles["Normal"],
    fontSize=12,
    fontName="Helvetica-Bold",
    textColor=DARK_GRAY,
)
MONO_STYLE = ParagraphStyle(
    "MonoStyle",
    parent=styles["Code"],
    fontSize=8,
    leading=11,
    fontName="Courier",
    textColor=DARK_GRAY,
)
LABEL_STYLE = ParagraphStyle(
    "LabelStyle",
    parent=styles["Normal"],
    fontSize=9,
    fontName="Helvetica-Bold",
    textColor=BRAND_BLUE,
)


def _logo_placeholder(width: float = 6 * cm, height: float = 1.5 * cm):
    """Return a Table acting as a logo placeholder box."""
    table = Table([[Paragraph("✈  AIRLINE LOGO", LABEL_STYLE)]], colWidths=[width], rowHeights=[height])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
        ("BOX", (0, 0), (-1, -1), 1, BRAND_BLUE),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return table


def _cta_button(cta_text: str, width: float = 8 * cm, height: float = 1.2 * cm):
    """Return a Table styled as a CTA button."""
    btn_style = ParagraphStyle(
        "CTAStyle",
        parent=styles["Normal"],
        fontSize=12,
        fontName="Helvetica-Bold",
        textColor=colors.white,
        alignment=1,
    )
    table = Table([[Paragraph(cta_text, btn_style)]], colWidths=[width], rowHeights=[height])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BRAND_ORANGE),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return table


def generate_campaign_pdf(campaign: dict, route: str, generated_at: str) -> io.BytesIO:
    """
    Generate the campaign PDF.

    Contents:
    - Airline logo placeholder
    - Title: "Marketing Campaign — {route}"
    - Generated date
    - Subject line (styled)
    - Preview text
    - Email body
    - CTA button (colored box)
    - Footer: "Generated by Marketing AI"

    Returns an in-memory BytesIO buffer ready for S3 upload.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             leftMargin=2 * cm, rightMargin=2 * cm,
                             topMargin=2 * cm, bottomMargin=2 * cm)
    story = []

    # Logo placeholder
    story.append(_logo_placeholder())
    story.append(Spacer(1, 0.5 * cm))

    # Title
    story.append(Paragraph(f"Marketing Campaign — {route}", TITLE_STYLE))
    story.append(Paragraph(f"Generated: {generated_at}", BODY_STYLE))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_BLUE))
    story.append(Spacer(1, 0.5 * cm))

    # Subject line
    story.append(Paragraph("Subject Line", HEADING_STYLE))
    story.append(Paragraph(campaign.get("subject_line", ""), SUBJECT_STYLE))
    story.append(Spacer(1, 0.3 * cm))

    # Preview text
    story.append(Paragraph("Preview Text", HEADING_STYLE))
    story.append(Paragraph(campaign.get("preview_text", ""), BODY_STYLE))
    story.append(Spacer(1, 0.3 * cm))

    # Email body
    story.append(Paragraph("Email Body", HEADING_STYLE))
    body_text = campaign.get("body", "").replace("\n", "<br/>")
    story.append(Paragraph(body_text, BODY_STYLE))
    story.append(Spacer(1, 0.8 * cm))

    # CTA button
    story.append(_cta_button(campaign.get("cta", "Learn More")))
    story.append(Spacer(1, 1 * cm))

    # Footer
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.gray))
    footer_style = ParagraphStyle("footer", parent=styles["Normal"], fontSize=8,
                                   textColor=colors.gray, alignment=1)
    story.append(Paragraph("Generated by Marketing AI", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer


def generate_metadata_pdf(metadata: dict) -> io.BytesIO:
    """
    Generate the metadata PDF.

    Sections:
    1. Campaign Parameters
    2. LLM Configuration
    3. Data Sources Used
    4. Full Prompt Used (monospace)
    5. Audience Summary

    Returns an in-memory BytesIO buffer ready for S3 upload.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             leftMargin=2 * cm, rightMargin=2 * cm,
                             topMargin=2 * cm, bottomMargin=2 * cm)
    story = []

    route = metadata.get("route", "Unknown")
    story.append(Paragraph(f"Campaign Metadata — {route}", TITLE_STYLE))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_BLUE))
    story.append(Spacer(1, 0.4 * cm))

    # Section 1 — Campaign Parameters
    story.append(Paragraph("1. Campaign Parameters", HEADING_STYLE))
    params = [
        ("Route", metadata.get("route", "")),
        ("Audience Description", metadata.get("audience_description", "")),
        ("Campaign Type", metadata.get("campaign_type", "")),
        ("Language", metadata.get("language", "")),
        ("Tone", metadata.get("tone", "")),
        ("Generated At", metadata.get("generated_at", "")),
    ]
    for label, value in params:
        story.append(Paragraph(f"<b>{label}:</b> {value}", BODY_STYLE))
    story.append(Spacer(1, 0.3 * cm))

    # Section 2 — LLM Configuration
    story.append(Paragraph("2. LLM Configuration", HEADING_STYLE))
    llm_params = [
        ("Model", metadata.get("model_id", "anthropic.claude-3-sonnet-20240229-v1:0")),
        ("Max Tokens Configured", str(metadata.get("max_tokens", 2048))),
        ("Tokens Consumed", str(metadata.get("tokens_used", 0))),
    ]
    for label, value in llm_params:
        story.append(Paragraph(f"<b>{label}:</b> {value}", BODY_STYLE))
    story.append(Spacer(1, 0.3 * cm))

    # Section 3 — Data Sources
    story.append(Paragraph("3. Data Sources Used", HEADING_STYLE))

    sql_queries = metadata.get("sql_queries", [])
    story.append(Paragraph("<b>PostgreSQL Queries Executed:</b>", BODY_STYLE))
    if sql_queries:
        for i, q in enumerate(sql_queries, 1):
            story.append(Paragraph(f"Query {i}:", LABEL_STYLE))
            story.append(Paragraph(q, MONO_STYLE))
    else:
        story.append(Paragraph("None", BODY_STYLE))

    story.append(Spacer(1, 0.2 * cm))
    csv_files = metadata.get("csv_files_used", [])
    story.append(Paragraph(f"<b>CSV Files Used:</b> {', '.join(csv_files) or 'None'}", BODY_STYLE))

    story.append(Spacer(1, 0.2 * cm))
    rag_chunks = metadata.get("rag_chunks", [])
    story.append(Paragraph("<b>PDF Documents Retrieved (RAG):</b>", BODY_STYLE))
    if rag_chunks:
        for chunk in rag_chunks:
            source = chunk.get("source_file", "unknown")
            excerpt = chunk.get("content_excerpt", "")[:150]
            story.append(Paragraph(f"<i>{source}</i>: {excerpt}...", BODY_STYLE))
    else:
        story.append(Paragraph("None", BODY_STYLE))
    story.append(Spacer(1, 0.3 * cm))

    # Section 4 — Full Prompt
    story.append(Paragraph("4. Full Prompt Used", HEADING_STYLE))
    full_prompt = metadata.get("full_prompt", "Not captured.")
    # Truncate if excessively long to keep PDF manageable
    if len(full_prompt) > 3000:
        full_prompt = full_prompt[:3000] + "\n... [truncated]"
    story.append(Paragraph(full_prompt.replace("\n", "<br/>"), MONO_STYLE))
    story.append(Spacer(1, 0.3 * cm))

    # Section 5 — Audience Summary
    story.append(Paragraph("5. Audience Summary", HEADING_STYLE))
    audience_data = metadata.get("audience_data", "No audience data available.")
    if len(audience_data) > 2000:
        audience_data = audience_data[:2000] + "\n... [truncated]"
    story.append(Paragraph(audience_data.replace("\n", "<br/>"), BODY_STYLE))

    doc.build(story)
    buffer.seek(0)
    return buffer
